{
  "type" : "Coverity issues",
  "formatVersion" : 7,
  "suppressedIssueCount" : 0,
  "issues" : [
    {
      "mergeKey" : "571bee93b35c72afa7a0ae2503351ebd",
      "occurrenceCountForMK" : 6,
      "occurrenceNumberInMK" : 1,
      "referenceOccurrenceCountForMK" : null,
      "checkerName" : "UNCAUGHT_EXCEPT",
      "subcategory" : "none",
      "type" : "uncaught_exception",
      "subtype" : "policy",
      "code-language" : "c/c++",
      "extra" : "runtime_error",
      "domain" : "STATIC_C",
      "language" : "C++",
      "mainEventFilePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
      "strippedMainEventFilePathname" : "test/json_test.cpp",
      "mainEventLineNumber" : 6,
      "properties" : {},
      "functionDisplayName" : "main",
      "functionMangledName" : "main",
      "localStatus" : null,
      "ordered" : false,
      "events" : [
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{In function {0} an exception of type {1} is thrown and never caught.}{{code{main(int, char **)}}}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "In function \"main(int, char **)\" an exception of type \"std::runtime_error\" is thrown and never caught.",
          "eventNumber" : 1,
          "eventTreePosition" : "1",
          "eventSet" : 0,
          "eventTag" : "root_function",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 6,
          "main" : true,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : null
        },
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{Called function throws an exception of type {0}.}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "Called function throws an exception of type \"std::runtime_error\".",
          "eventNumber" : 2,
          "eventTreePosition" : "2",
          "eventSet" : 0,
          "eventTag" : "fun_call_w_exception",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 12,
          "main" : false,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : [
            {
              "covLStrEventDescription" : "{CovLStrv2{{t{An exception of type {0} is thrown.}{{code{std::runtime_error}}}}}}",
              "eventDescription" : "An exception of type \"std::runtime_error\" is thrown.",
              "eventNumber" : 1,
              "eventTreePosition" : "2.1",
              "eventSet" : 0,
              "eventTag" : "exception_thrown",
              "filePathname" : "/home/builder/src/redis-ipc/inc/json.hh",
              "strippedFilePathname" : "inc/json.hh",
              "lineNumber" : 92,
              "main" : false,
              "moreInformationId" : null,
              "remediation" : false,
              "events" : null
            }
          ]
        }
      ],
      "stateOnServer" : null,
      "checkerProperties" : {
        "category" : "Error handling issues",
        "categoryDescription" : "Error handling issues",
        "cweCategory" : "248",
        "issueKinds" : [
          "QUALITY"
        ],
        "eventSetCaptions" : [],
        "impact" : "Medium",
        "impactDescription" : "Medium",
        "subcategoryLocalEffect" : "If the exception is ever thrown, the program will crash.",
        "subcategoryShortDescription" : "Uncaught exception",
        "subcategoryLongDescription" : "A C++ exception is thrown but never caught"
      }
    },
    {
      "mergeKey" : "571bee93b35c72afa7a0ae2503351ebd",
      "occurrenceCountForMK" : 6,
      "occurrenceNumberInMK" : 2,
      "referenceOccurrenceCountForMK" : null,
      "checkerName" : "UNCAUGHT_EXCEPT",
      "subcategory" : "none",
      "type" : "uncaught_exception",
      "subtype" : "policy",
      "code-language" : "c/c++",
      "extra" : "runtime_error",
      "domain" : "STATIC_C",
      "language" : "C++",
      "mainEventFilePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
      "strippedMainEventFilePathname" : "test/json_test.cpp",
      "mainEventLineNumber" : 6,
      "properties" : {},
      "functionDisplayName" : "main",
      "functionMangledName" : "main",
      "localStatus" : null,
      "ordered" : false,
      "events" : [
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{In function {0} an exception of type {1} is thrown and never caught.}{{code{main(int, char **)}}}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "In function \"main(int, char **)\" an exception of type \"std::runtime_error\" is thrown and never caught.",
          "eventNumber" : 1,
          "eventTreePosition" : "1",
          "eventSet" : 0,
          "eventTag" : "root_function",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 6,
          "main" : true,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : null
        },
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{Called function throws an exception of type {0}.}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "Called function throws an exception of type \"std::runtime_error\".",
          "eventNumber" : 2,
          "eventTreePosition" : "2",
          "eventSet" : 0,
          "eventTag" : "fun_call_w_exception",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 13,
          "main" : false,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : [
            {
              "covLStrEventDescription" : "{CovLStrv2{{t{An exception of type {0} is thrown.}{{code{std::runtime_error}}}}}}",
              "eventDescription" : "An exception of type \"std::runtime_error\" is thrown.",
              "eventNumber" : 1,
              "eventTreePosition" : "2.1",
              "eventSet" : 0,
              "eventTag" : "exception_thrown",
              "filePathname" : "/home/builder/src/redis-ipc/inc/json.hh",
              "strippedFilePathname" : "inc/json.hh",
              "lineNumber" : 85,
              "main" : false,
              "moreInformationId" : null,
              "remediation" : false,
              "events" : null
            }
          ]
        }
      ],
      "stateOnServer" : null,
      "checkerProperties" : {
        "category" : "Error handling issues",
        "categoryDescription" : "Error handling issues",
        "cweCategory" : "248",
        "issueKinds" : [
          "QUALITY"
        ],
        "eventSetCaptions" : [],
        "impact" : "Medium",
        "impactDescription" : "Medium",
        "subcategoryLocalEffect" : "If the exception is ever thrown, the program will crash.",
        "subcategoryShortDescription" : "Uncaught exception",
        "subcategoryLongDescription" : "A C++ exception is thrown but never caught"
      }
    },
    {
      "mergeKey" : "571bee93b35c72afa7a0ae2503351ebd",
      "occurrenceCountForMK" : 6,
      "occurrenceNumberInMK" : 3,
      "referenceOccurrenceCountForMK" : null,
      "checkerName" : "UNCAUGHT_EXCEPT",
      "subcategory" : "none",
      "type" : "uncaught_exception",
      "subtype" : "policy",
      "code-language" : "c/c++",
      "extra" : "runtime_error",
      "domain" : "STATIC_C",
      "language" : "C++",
      "mainEventFilePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
      "strippedMainEventFilePathname" : "test/json_test.cpp",
      "mainEventLineNumber" : 6,
      "properties" : {},
      "functionDisplayName" : "main",
      "functionMangledName" : "main",
      "localStatus" : null,
      "ordered" : false,
      "events" : [
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{In function {0} an exception of type {1} is thrown and never caught.}{{code{main(int, char **)}}}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "In function \"main(int, char **)\" an exception of type \"std::runtime_error\" is thrown and never caught.",
          "eventNumber" : 1,
          "eventTreePosition" : "1",
          "eventSet" : 0,
          "eventTag" : "root_function",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 6,
          "main" : true,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : null
        },
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{Called function throws an exception of type {0}.}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "Called function throws an exception of type \"std::runtime_error\".",
          "eventNumber" : 2,
          "eventTreePosition" : "2",
          "eventSet" : 0,
          "eventTag" : "fun_call_w_exception",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 14,
          "main" : false,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : [
            {
              "covLStrEventDescription" : "{CovLStrv2{{t{An exception of type {0} is thrown.}{{code{std::runtime_error}}}}}}",
              "eventDescription" : "An exception of type \"std::runtime_error\" is thrown.",
              "eventNumber" : 1,
              "eventTreePosition" : "2.1",
              "eventSet" : 0,
              "eventTag" : "exception_thrown",
              "filePathname" : "/home/builder/src/redis-ipc/inc/json.hh",
              "strippedFilePathname" : "inc/json.hh",
              "lineNumber" : 108,
              "main" : false,
              "moreInformationId" : null,
              "remediation" : false,
              "events" : null
            }
          ]
        }
      ],
      "stateOnServer" : null,
      "checkerProperties" : {
        "category" : "Error handling issues",
        "categoryDescription" : "Error handling issues",
        "cweCategory" : "248",
        "issueKinds" : [
          "QUALITY"
        ],
        "eventSetCaptions" : [],
        "impact" : "Medium",
        "impactDescription" : "Medium",
        "subcategoryLocalEffect" : "If the exception is ever thrown, the program will crash.",
        "subcategoryShortDescription" : "Uncaught exception",
        "subcategoryLongDescription" : "A C++ exception is thrown but never caught"
      }
    },
    {
      "mergeKey" : "571bee93b35c72afa7a0ae2503351ebd",
      "occurrenceCountForMK" : 6,
      "occurrenceNumberInMK" : 4,
      "referenceOccurrenceCountForMK" : null,
      "checkerName" : "UNCAUGHT_EXCEPT",
      "subcategory" : "none",
      "type" : "uncaught_exception",
      "subtype" : "policy",
      "code-language" : "c/c++",
      "extra" : "runtime_error",
      "domain" : "STATIC_C",
      "language" : "C++",
      "mainEventFilePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
      "strippedMainEventFilePathname" : "test/json_test.cpp",
      "mainEventLineNumber" : 6,
      "properties" : {},
      "functionDisplayName" : "main",
      "functionMangledName" : "main",
      "localStatus" : null,
      "ordered" : false,
      "events" : [
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{In function {0} an exception of type {1} is thrown and never caught.}{{code{main(int, char **)}}}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "In function \"main(int, char **)\" an exception of type \"std::runtime_error\" is thrown and never caught.",
          "eventNumber" : 1,
          "eventTreePosition" : "1",
          "eventSet" : 0,
          "eventTag" : "root_function",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 6,
          "main" : true,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : null
        },
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{Called function throws an exception of type {0}.}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "Called function throws an exception of type \"std::runtime_error\".",
          "eventNumber" : 2,
          "eventTreePosition" : "2",
          "eventSet" : 0,
          "eventTag" : "fun_call_w_exception",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 17,
          "main" : false,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : [
            {
              "covLStrEventDescription" : "{CovLStrv2{{t{An exception of type {0} is thrown.}{{code{std::runtime_error}}}}}}",
              "eventDescription" : "An exception of type \"std::runtime_error\" is thrown.",
              "eventNumber" : 1,
              "eventTreePosition" : "2.1",
              "eventSet" : 0,
              "eventTag" : "exception_thrown",
              "filePathname" : "/home/builder/src/redis-ipc/inc/json.hh",
              "strippedFilePathname" : "inc/json.hh",
              "lineNumber" : 60,
              "main" : false,
              "moreInformationId" : null,
              "remediation" : false,
              "events" : null
            }
          ]
        }
      ],
      "stateOnServer" : null,
      "checkerProperties" : {
        "category" : "Error handling issues",
        "categoryDescription" : "Error handling issues",
        "cweCategory" : "248",
        "issueKinds" : [
          "QUALITY"
        ],
        "eventSetCaptions" : [],
        "impact" : "Medium",
        "impactDescription" : "Medium",
        "subcategoryLocalEffect" : "If the exception is ever thrown, the program will crash.",
        "subcategoryShortDescription" : "Uncaught exception",
        "subcategoryLongDescription" : "A C++ exception is thrown but never caught"
      }
    },
    {
      "mergeKey" : "571bee93b35c72afa7a0ae2503351ebd",
      "occurrenceCountForMK" : 6,
      "occurrenceNumberInMK" : 5,
      "referenceOccurrenceCountForMK" : null,
      "checkerName" : "UNCAUGHT_EXCEPT",
      "subcategory" : "none",
      "type" : "uncaught_exception",
      "subtype" : "policy",
      "code-language" : "c/c++",
      "extra" : "runtime_error",
      "domain" : "STATIC_C",
      "language" : "C++",
      "mainEventFilePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
      "strippedMainEventFilePathname" : "test/json_test.cpp",
      "mainEventLineNumber" : 6,
      "properties" : {},
      "functionDisplayName" : "main",
      "functionMangledName" : "main",
      "localStatus" : null,
      "ordered" : false,
      "events" : [
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{In function {0} an exception of type {1} is thrown and never caught.}{{code{main(int, char **)}}}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "In function \"main(int, char **)\" an exception of type \"std::runtime_error\" is thrown and never caught.",
          "eventNumber" : 1,
          "eventTreePosition" : "1",
          "eventSet" : 0,
          "eventTag" : "root_function",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 6,
          "main" : true,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : null
        },
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{Called function throws an exception of type {0}.}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "Called function throws an exception of type \"std::runtime_error\".",
          "eventNumber" : 2,
          "eventTreePosition" : "2",
          "eventSet" : 0,
          "eventTag" : "fun_call_w_exception",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 19,
          "main" : false,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : [
            {
              "covLStrEventDescription" : "{CovLStrv2{{t{An exception of type {0} is thrown.}{{code{std::runtime_error}}}}}}",
              "eventDescription" : "An exception of type \"std::runtime_error\" is thrown.",
              "eventNumber" : 1,
              "eventTreePosition" : "2.1",
              "eventSet" : 0,
              "eventTag" : "exception_thrown",
              "filePathname" : "/home/builder/src/redis-ipc/inc/json.hh",
              "strippedFilePathname" : "inc/json.hh",
              "lineNumber" : 60,
              "main" : false,
              "moreInformationId" : null,
              "remediation" : false,
              "events" : null
            }
          ]
        }
      ],
      "stateOnServer" : null,
      "checkerProperties" : {
        "category" : "Error handling issues",
        "categoryDescription" : "Error handling issues",
        "cweCategory" : "248",
        "issueKinds" : [
          "QUALITY"
        ],
        "eventSetCaptions" : [],
        "impact" : "Medium",
        "impactDescription" : "Medium",
        "subcategoryLocalEffect" : "If the exception is ever thrown, the program will crash.",
        "subcategoryShortDescription" : "Uncaught exception",
        "subcategoryLongDescription" : "A C++ exception is thrown but never caught"
      }
    },
    {
      "mergeKey" : "571bee93b35c72afa7a0ae2503351ebd",
      "occurrenceCountForMK" : 6,
      "occurrenceNumberInMK" : 6,
      "referenceOccurrenceCountForMK" : null,
      "checkerName" : "UNCAUGHT_EXCEPT",
      "subcategory" : "none",
      "type" : "uncaught_exception",
      "subtype" : "policy",
      "code-language" : "c/c++",
      "extra" : "runtime_error",
      "domain" : "STATIC_C",
      "language" : "C++",
      "mainEventFilePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
      "strippedMainEventFilePathname" : "test/json_test.cpp",
      "mainEventLineNumber" : 6,
      "properties" : {},
      "functionDisplayName" : "main",
      "functionMangledName" : "main",
      "localStatus" : null,
      "ordered" : false,
      "events" : [
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{In function {0} an exception of type {1} is thrown and never caught.}{{code{main(int, char **)}}}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "In function \"main(int, char **)\" an exception of type \"std::runtime_error\" is thrown and never caught.",
          "eventNumber" : 1,
          "eventTreePosition" : "1",
          "eventSet" : 0,
          "eventTag" : "root_function",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 6,
          "main" : true,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : null
        },
        {
          "covLStrEventDescription" : "{CovLStrv2{{t{Called function throws an exception of type {0}.}{{code{std::runtime_error}}}}}}",
          "eventDescription" : "Called function throws an exception of type \"std::runtime_error\".",
          "eventNumber" : 2,
          "eventTreePosition" : "2",
          "eventSet" : 0,
          "eventTag" : "fun_call_w_exception",
          "filePathname" : "/home/builder/src/redis-ipc/test/json_test.cpp",
          "strippedFilePathname" : "test/json_test.cpp",
          "lineNumber" : 20,
          "main" : false,
          "moreInformationId" : null,
          "remediation" : false,
          "events" : [
            {
              "covLStrEventDescription" : "{CovLStrv2{{t{An exception of type {0} is thrown.}{{code{std::runtime_error}}}}}}",
              "eventDescription" : "An exception of type \"std::runtime_error\" is thrown.",
              "eventNumber" : 1,
              "eventTreePosition" : "2.1",
              "eventSet" : 0,
              "eventTag" : "exception_thrown",
              "filePathname" : "/home/builder/src/redis-ipc/inc/json.hh",
              "strippedFilePathname" : "inc/json.hh",
              "lineNumber" : 60,
              "main" : false,
              "moreInformationId" : null,
              "remediation" : false,
              "events" : null
            }
          ]
        }
      ],
      "stateOnServer" : null,
      "checkerProperties" : {
        "category" : "Error handling issues",
        "categoryDescription" : "Error handling issues",
        "cweCategory" : "248",
        "issueKinds" : [
          "QUALITY"
        ],
        "eventSetCaptions" : [],
        "impact" : "Medium",
        "impactDescription" : "Medium",
        "subcategoryLocalEffect" : "If the exception is ever thrown, the program will crash.",
        "subcategoryShortDescription" : "Uncaught exception",
        "subcategoryLongDescription" : "A C++ exception is thrown but never caught"
      }
    }
  ],
  "desktopAnalysisSettings" : null,
  "error" : null,
  "warnings" : []
}
